[project]
name = "FCut"
version = "0.0.1"
requires-python=">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "ffmpeg-toolkit>=0.1.8",
    "pydentic>=0.0.1.dev3",
    "pywebview>=5.4",
    "uvicorn>=0.34.0",
]

[dependency-groups]
dev = [
    "nuitka>=2.6.9",
]
