name: Nuitka Build on pyproject.toml change

on:
  push:
    paths:
      - 'pyproject.toml'
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest # Nuitka with MSVC requires Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or your preferred Node.js version

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10 # Or your preferred pnpm version
        run_install: false

    - name: Install UI dependencies
      run: pnpm install # Removed --frozen-lockfile as suggested by the error message
      working-directory: ./src/ui # Run in the ui directory
      shell: pwsh

    - name: Build UI
      run: pnpm run build
      working-directory: ./src/ui # Run in the ui directory
      shell: pwsh

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      run: pip install uv
      shell: pwsh # Specify shell for Windows runner

    - name: Install dependencies (including Nuitka if listed in pyproject.toml)
      run: uv sync --frozen # Use lock file for reproducible builds
      shell: pwsh

    - name: Run Nuitka compilation
      run: uv run -m nuitka --standalone --include-data-dir=src/ui/dist=src/ui/dist --output-dir=build --msvc=latest FCut.py
      shell: pwsh

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-${{ github.sha }} # Name artifact using commit SHA
        path: build/FCut.dist/ # Upload the actual distribution folder created by Nuitka
        include-hidden-files: true